"""Reports / configurable widget dashboard schemas.

Per-widget config schemas live under `widgets/`; `DashboardConfig`
glues them into a discriminated union with overlap/bounds/max-widgets
validation.
"""

# Legacy report schemas (kpi-summary / leaderboard / loss-reasons /
# pipeline-velocity / team-leaderboard / my-summary). Kept in-tree so
# the salesperson dashboard and existing tests stay green; the new
# widget endpoints (R2+) live alongside under widgets/.
from app.schemas.reports.legacy import (
    KpiSummary,
    Leaderboard,
    LeaderboardRow,
    LossReasonRow,
    LossReasons,
    MySummary,
    TeamLeaderboard,
    TeamLeaderboardRow,
    TeamMetric,
    Velocity,
    VelocityByStage,
)

from app.schemas.reports.dashboard import (
    GRID_COLUMNS,
    MAX_WIDGETS,
    DashboardConfig,
    DateRangeFilter,
    GlobalFilters,
    WidgetConfig,
    WidgetEntry,
    WidgetPosition,
)
from app.schemas.reports.responses import (
    AvgDealSizeResponse,
    CompaniesAtRiskResponse,
    CompanyAtRiskItem,
    Comparison,
    DealsWonResponse,
    LeadConversionBreakdownItem,
    LeadToDealConversionResponse,
    LostReasonItem,
    LostReasonsBreakdownResponse,
    NewCompaniesBreakdownItem,
    NewCompaniesResponse,
    PipelineValueResponse,
    RepActivityItem,
    RepActivityResponse,
    SalesCycleLengthResponse,
    SalesLeaderboardItem,
    SalesLeaderboardResponse,
    SparklineBucket,
    StaleDealItem,
    StaleDealsResponse,
    WinRateResponse,
)
from app.schemas.reports.widgets import (
    AvgDealSizeConfig,
    CompaniesAtRiskConfig,
    DealsWonConfig,
    LeadToDealConversionConfig,
    LostReasonsBreakdownConfig,
    NewCompaniesConfig,
    PipelineValueConfig,
    RepActivityConfig,
    SalesCycleLengthConfig,
    SalesLeaderboardConfig,
    StaleDealsConfig,
    WidgetType,
    WinRateConfig,
)

__all__ = [
    "AvgDealSizeConfig",
    "AvgDealSizeResponse",
    "CompaniesAtRiskConfig",
    "CompaniesAtRiskResponse",
    "CompanyAtRiskItem",
    "Comparison",
    "DashboardConfig",
    "DateRangeFilter",
    "DealsWonConfig",
    "DealsWonResponse",
    "GRID_COLUMNS",
    "GlobalFilters",
    "KpiSummary",
    "Leaderboard",
    "LeaderboardRow",
    "LeadConversionBreakdownItem",
    "LeadToDealConversionConfig",
    "LeadToDealConversionResponse",
    "LossReasonRow",
    "LossReasons",
    "LostReasonItem",
    "LostReasonsBreakdownConfig",
    "LostReasonsBreakdownResponse",
    "MAX_WIDGETS",
    "MySummary",
    "NewCompaniesBreakdownItem",
    "NewCompaniesConfig",
    "NewCompaniesResponse",
    "PipelineValueConfig",
    "PipelineValueResponse",
    "RepActivityConfig",
    "RepActivityItem",
    "RepActivityResponse",
    "SalesCycleLengthConfig",
    "SalesCycleLengthResponse",
    "SalesLeaderboardConfig",
    "SalesLeaderboardItem",
    "SalesLeaderboardResponse",
    "SparklineBucket",
    "StaleDealItem",
    "StaleDealsConfig",
    "StaleDealsResponse",
    "TeamLeaderboard",
    "TeamLeaderboardRow",
    "TeamMetric",
    "Velocity",
    "VelocityByStage",
    "WidgetConfig",
    "WidgetEntry",
    "WidgetPosition",
    "WidgetType",
    "WinRateConfig",
    "WinRateResponse",
]
