#!/usr/bin/env python3
"""Generate an Entity-Relationship Diagram from the SQLAlchemy metadata.

Emits two pure-text artifacts that don't need a graphviz install:
  * docs/ERD.md   — Mermaid `erDiagram` block; GitHub renders it inline.
  * docs/schema.dbml — DBML; paste into https://dbdiagram.io for an
                       interactive zoomable view.

Run from the repo root:

    uv run --project backend python scripts/generate_erd.py

Optional SVG path (requires `graphviz` system package + `eralchemy2`):

    apt install graphviz graphviz-dev
    uv add --project backend --dev eralchemy2
    uv run --project backend python scripts/generate_erd.py --svg

The SVG path is opt-in because pygraphviz fails to build without graphviz
dev headers, which we don't want to require for normal dev work.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

# Import the Base after extending sys.path. The model modules register
# themselves on Base.metadata via SQLAlchemy's declarative side effect,
# so importing the package is enough.
from app.db import models  # noqa: E402, F401  (side-effect: register tables)
from app.db.base import Base  # noqa: E402
from sqlalchemy import Column, ForeignKey  # noqa: E402
from sqlalchemy.sql.schema import Table  # noqa: E402

DOCS_DIR = REPO_ROOT / "docs"
MERMAID_PATH = DOCS_DIR / "ERD.md"
DBML_PATH = DOCS_DIR / "schema.dbml"


def _column_type(column: Column[object]) -> str:
    raw = type(column.type).__name__
    return raw.lower().replace(" ", "_")


def _fk_target(column: Column[object]) -> tuple[str, str] | None:
    for fk in column.foreign_keys:
        target = fk.column
        if isinstance(target.table, Table):
            return target.table.name, target.name
    return None


def render_mermaid(metadata: Base.metadata.__class__) -> str:
    lines: list[str] = ["erDiagram"]
    relations: list[str] = []

    for table in sorted(metadata.tables.values(), key=lambda t: t.name):
        lines.append(f"    {table.name} {{")
        for column in table.columns:
            type_name = _column_type(column)
            markers: list[str] = []
            if column.primary_key:
                markers.append("PK")
            target = _fk_target(column)
            if target is not None:
                markers.append("FK")
            marker = f" {','.join(markers)}" if markers else ""
            lines.append(f"        {type_name} {column.name}{marker}")
        lines.append("    }")

    for table in sorted(metadata.tables.values(), key=lambda t: t.name):
        for column in table.columns:
            target = _fk_target(column)
            if target is None:
                continue
            target_table, _target_col = target
            # `}o--||` reads as "many on the FK side, exactly one on the
            # target side". Nullable FKs are "}o--o|"; we keep the diagram
            # readable by always using the more common many-to-one form.
            cardinality = "}o--||" if not column.nullable else "}o--o|"
            relations.append(f"    {table.name} {cardinality} {target_table} : {column.name}")

    if relations:
        lines.append("")
        lines.extend(sorted(set(relations)))
    return "\n".join(lines)


def render_dbml(metadata: Base.metadata.__class__) -> str:
    lines: list[str] = []
    for table in sorted(metadata.tables.values(), key=lambda t: t.name):
        lines.append(f"Table {table.name} {{")
        for column in table.columns:
            type_name = _column_type(column)
            attrs: list[str] = []
            if column.primary_key:
                attrs.append("pk")
            if not column.nullable and not column.primary_key:
                attrs.append("not null")
            attr_block = f" [{', '.join(attrs)}]" if attrs else ""
            lines.append(f"  {column.name} {type_name}{attr_block}")
        lines.append("}")
        lines.append("")

    for table in sorted(metadata.tables.values(), key=lambda t: t.name):
        for column in table.columns:
            for fk in column.foreign_keys:
                if not isinstance(fk.column.table, Table):
                    continue
                target = fk.column
                lines.append(
                    f"Ref: {table.name}.{column.name} > {target.table.name}.{target.name}"
                )
    return "\n".join(lines)


MERMAID_PREAMBLE = """# Entity-Relationship Diagram

Auto-generated by `scripts/generate_erd.py`. Do not edit by hand.
Re-run after schema changes:

```sh
uv run --project backend python scripts/generate_erd.py
```

GitHub renders the Mermaid block below inline. For an interactive
zoomable view, paste `docs/schema.dbml` into <https://dbdiagram.io>.

```mermaid
"""

MERMAID_POSTAMBLE = "\n```\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--svg",
        action="store_true",
        help="also emit docs/erd.svg via eralchemy2 (requires graphviz + eralchemy2)",
    )
    args = parser.parse_args()

    DOCS_DIR.mkdir(exist_ok=True)
    mermaid = render_mermaid(Base.metadata)
    MERMAID_PATH.write_text(MERMAID_PREAMBLE + mermaid + MERMAID_POSTAMBLE, encoding="utf-8")
    print(f"wrote {MERMAID_PATH.relative_to(REPO_ROOT)}")

    dbml = render_dbml(Base.metadata)
    DBML_PATH.write_text(dbml + "\n", encoding="utf-8")
    print(f"wrote {DBML_PATH.relative_to(REPO_ROOT)}")

    if args.svg:
        try:
            from eralchemy2 import render_er  # type: ignore[import-not-found]
        except ImportError:
            print(
                "--svg requested but eralchemy2 isn't installed; "
                "install with: uv add --project backend --dev eralchemy2",
                file=sys.stderr,
            )
            return 1
        svg_path = DOCS_DIR / "erd.svg"
        render_er(Base.metadata, str(svg_path))
        print(f"wrote {svg_path.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
