/**
 * Centralized `data-testid` map.
 *
 * Why central:
 *   1. Stable selectors for E2E tests (Playwright) and for AI agents
 *      driving the app via Playwright MCP — the values don't drift when
 *      copy or markup changes.
 *   2. One place to read when picking a new testid so we don't fork
 *      naming conventions across the codebase.
 *
 * Convention: `{page-or-area}-{component}-{action-or-role}` in
 * kebab-case. Functions accept dynamic IDs as suffixes and return a
 * fully-resolved string (e.g. `pipelineStage("s1") → "pipeline-stage-s1"`).
 *
 * Tag interactive primitives only — buttons users click, inputs they
 * fill, items they select. Don't tag layout-only nodes.
 */
export const testIds = {
  nav: {
    overview: "nav-overview",
    pipeline: "nav-pipeline",
    companies: "nav-companies",
    contacts: "nav-contacts",
    deals: "nav-deals",
    emails: "nav-emails",
    calendar: "nav-calendar",
    reports: "nav-reports",
    settings: "nav-settings",
  },
  pwa: {
    nudge: "pwa-nudge",
    nudgeInstall: "pwa-nudge-install",
    nudgeLater: "pwa-nudge-later",
    nudgeNever: "pwa-nudge-never",
    moreInstall: "pwa-more-install",
    settingsInstall: "pwa-settings-install",
    iosModalClose: "pwa-ios-modal-close",
  },
  search: {
    input: "global-search-input",
    mobileToggle: "global-search-toggle",
    panel: "global-search-panel",
    option: (id: string) => `global-search-option-${id}`,
  },
  companies: {
    addButton: "companies-add-button",
    bulkEmailButton: "companies-bulk-email-button",
    ownerFilter: "companies-owner-filter",
    openDealsFilter: "companies-open-deals-filter",
    deleteButton: "companies-delete-button",
    contactRowView: (id: string) => `company-contact-view-${id}`,
    contactRowEdit: (id: string) => `company-contact-edit-${id}`,
    contactRowDelete: (id: string) => `company-contact-delete-${id}`,
    addModal: {
      icoInput: "companies-add-modal-ico",
      nameInput: "companies-add-modal-name",
      emailInput: "companies-add-modal-email",
      websiteInput: "companies-add-modal-website",
      submit: "companies-add-modal-submit",
      cancel: "companies-add-modal-cancel",
    },
    editButton: "companies-edit-button",
    editModal: {
      nameInput: "companies-edit-modal-name",
      icoInput: "companies-edit-modal-ico",
      phoneInput: "companies-edit-modal-phone",
      ownerSelect: "companies-edit-modal-owner",
      submit: "companies-edit-modal-submit",
      cancel: "companies-edit-modal-cancel",
    },
  },
  contacts: {
    addButton: "contacts-add-button",
    exportCsv: "contacts-export-csv",
    openDealsFilter: "contacts-open-deals-filter",
    deleteButton: "contacts-delete-button",
    addModal: {
      firstNameInput: "contacts-add-modal-first-name",
      lastNameInput: "contacts-add-modal-last-name",
      emailInput: "contacts-add-modal-email",
      submit: "contacts-add-modal-submit",
      cancel: "contacts-add-modal-cancel",
    },
    editButton: "contacts-edit-button",
    editModal: {
      firstNameInput: "contacts-edit-modal-first-name",
      lastNameInput: "contacts-edit-modal-last-name",
      positionInput: "contacts-edit-modal-position",
      phoneInput: "contacts-edit-modal-phone",
      companyChange: "contacts-edit-modal-company-change",
      companyRemove: "contacts-edit-modal-company-remove",
      submit: "contacts-edit-modal-submit",
      cancel: "contacts-edit-modal-cancel",
    },
    viewModal: {
      close: "contacts-view-modal-close",
      edit: "contacts-view-modal-edit",
    },
  },
  deals: {
    addButton: "deals-add-button",
    exportCsv: "deals-export-csv",
    searchInput: "deals-search-input",
    stageFilter: "deals-stage-filter",
    ownerFilter: "deals-owner-filter",
    statusFilter: "deals-status-filter",
    clearFilters: "deals-clear-filters",
    sortHeader: (key: string) => `deals-sort-${key}`,
    row: (id: string) => `deals-row-${id}`,
    detail: {
      dialog: "deals-detail-dialog",
      timeline: "deals-detail-timeline",
      // The standing description (`deals.note`), not the activity timeline.
      noteEdit: "deals-detail-note-edit",
      noteInput: "deals-detail-note-input",
      noteSave: "deals-detail-note-save",
      noteCancel: "deals-detail-note-cancel",
      deleteButton: "deals-detail-delete-button",
      timelineLoadMore: "deals-detail-timeline-load-more",
    },
    addModal: {
      nameInput: "deals-add-modal-name",
      companyInput: "deals-add-modal-company-search",
      newCompanyToggle: "deals-add-modal-new-company-toggle",
      stageSelect: "deals-add-modal-stage",
      submit: "deals-add-modal-submit",
      cancel: "deals-add-modal-cancel",
      missingSummary: "deals-add-modal-missing",
    },
  },
  pipeline: {
    stage: (stageId: string) => `pipeline-stage-${stageId}`,
    deal: (dealId: string) => `pipeline-deal-${dealId}`,
    quickActions: {
      trigger: (dealId: string) => `pipeline-quick-actions-${dealId}`,
      modal: "pipeline-quick-actions-modal",
      email: "pipeline-quick-actions-email",
      event: "pipeline-quick-actions-event",
      note: "pipeline-quick-actions-note",
      noteInput: "pipeline-quick-actions-note-input",
      noteSave: "pipeline-quick-actions-note-save",
      noteCancel: "pipeline-quick-actions-note-cancel",
      call: "pipeline-quick-actions-call",
      callInput: "pipeline-quick-actions-call-input",
      callSave: "pipeline-quick-actions-call-save",
      close: "pipeline-quick-actions-close",
      followupSchedule: "pipeline-quick-actions-followup-schedule",
      followupDismiss: "pipeline-quick-actions-followup-dismiss",
    },
    preview: {
      popover: "pipeline-deal-preview",
    },
    loseZone: "pipeline-lose-zone",
    rottingBadge: (dealId: string) => `pipeline-rotting-${dealId}`,
    nextStep: (dealId: string) => `pipeline-next-step-${dealId}`,
    wonWindow: "pipeline-won-window",
    noNextStepFilter: "pipeline-no-next-step-filter",
  },
  confirmDialog: {
    confirm: "confirm-dialog-confirm",
    cancel: "confirm-dialog-cancel",
  },
  emails: {
    mail: {
      searchInput: "mail-search-input",
      typeFilter: "mail-type-filter",
      companyFilter: "mail-company-filter",
      dealFilter: "mail-deal-filter",
      mineToggle: "mail-mine-toggle",
      helpButton: "mail-help-button",
      helpDialog: "mail-help-dialog",
      row: (id: string) => `mail-row-${id}`,
      detailDialog: "mail-detail-dialog",
      detailReply: "mail-detail-reply",
      linkButton: (id: string) => `mail-link-${id}`,
      linkDialog: "mail-link-dialog",
      linkDealSelect: "mail-link-deal-select",
      linkSubmit: "mail-link-submit",
    },
    compose: {
      toInput: "email-compose-to-input",
      ccInput: "email-compose-cc-input",
      bccInput: "email-compose-bcc-input",
      trackToggle: "email-compose-track-toggle",
      templateSelect: "email-compose-template-select",
      attachDealToggle: "email-compose-attach-deal-toggle",
      attachDealSelect: "email-compose-attach-deal-select",
      suggestion: (field: string, contactId: string) =>
        `email-compose-${field}-suggestion-${contactId}`,
      newContactToggle: (field: string) => `email-compose-${field}-new-contact-toggle`,
      newContact: {
        firstNameInput: "email-compose-new-contact-first-name",
        lastNameInput: "email-compose-new-contact-last-name",
        emailInput: "email-compose-new-contact-email",
        save: "email-compose-new-contact-save",
        cancel: "email-compose-new-contact-cancel",
      },
    },
    bulkWizard: {
      templateSelect: "bulk-email-template-select",
    },
    history: {
      row: (id: string) => `email-history-row-${id}`,
      inboundBadge: (id: string) => `email-history-inbound-badge-${id}`,
    },
  },
  settings: {
    smtpSignature: "settings-smtp-signature",
    inboundAddress: {
      value: "settings-inbound-address-value",
      copy: "settings-inbound-address-copy",
      rotate: "settings-inbound-address-rotate",
    },
    emailTrackingToggle: "settings-email-tracking-toggle",
    dealRottingDaysInput: "settings-deal-rotting-days",
    salesGoals: {
      add: "settings-sales-goals-add",
      row: (id: string) => `settings-sales-goal-row-${id}`,
      edit: (id: string) => `settings-sales-goal-edit-${id}`,
      remove: (id: string) => `settings-sales-goal-delete-${id}`,
      userSelect: "settings-sales-goal-user",
      metricSelect: "settings-sales-goal-metric",
      targetInput: "settings-sales-goal-target",
      save: "settings-sales-goal-save",
      cancel: "settings-sales-goal-cancel",
    },
    emailTemplates: {
      add: "settings-email-templates-add",
      row: (id: string) => `settings-email-template-row-${id}`,
      edit: (id: string) => `settings-email-template-edit-${id}`,
      remove: (id: string) => `settings-email-template-delete-${id}`,
      nameInput: "settings-email-template-name",
      subjectInput: "settings-email-template-subject",
      bodyInput: "settings-email-template-body",
      save: "settings-email-template-save",
      cancel: "settings-email-template-cancel",
      mergeChip: (key: string) => `settings-email-template-merge-${key}`,
    },
  },
  reports: {
    addWidget: "reports-add-widget",
    editLayout: "reports-edit-layout",
    exportCsv: "reports-export-csv",
    filterBar: "reports-filter-bar",
  },
  dashboard: {
    editLayout: "dashboard-edit-layout",
    addWidget: "dashboard-add-widget",
    quickAction: (type: string) => `dashboard-quick-action-${type}`,
    widgetRemove: (id: string) => `dashboard-widget-remove-${id}`,
    widgetConfig: {
      open: (id: string) => `dashboard-widget-config-open-${id}`,
      popover: "dashboard-widget-config-popover",
      preset: (preset: string) => `dashboard-widget-config-preset-${preset}`,
    },
  },
  events: {
    dealPicker: {
      input: "event-form-deal-picker-input",
      option: (id: string) => `event-form-deal-picker-option-${id}`,
    },
    reconnectGoogle: "event-form-reconnect-google",
  },
  calendar: {
    newEvent: "calendar-new-event",
    scheduleDay: "calendar-schedule-day",
    emptySchedule: "calendar-empty-schedule",
    prevPeriod: "calendar-prev-period",
    nextPeriod: "calendar-next-period",
    today: "calendar-today",
    zoomWeek: "calendar-zoom-week",
    zoomMonth: "calendar-zoom-month",
    reconnect: "calendar-reconnect",
  },
  widgets: {
    picker: {
      modal: "widget-picker-modal",
      close: "widget-picker-close",
      item: (type: string) => `widget-picker-item-${type}`,
    },
    mobileList: {
      dragHandle: (id: string) => `widget-mobile-drag-${id}`,
      moveUp: (id: string) => `widget-mobile-move-up-${id}`,
      moveDown: (id: string) => `widget-mobile-move-down-${id}`,
    },
  },
  onboarding: {
    wizard: {
      nameInput: "onboarding-name-input",
      seatCountInput: "onboarding-seat-count-input",
      next: "onboarding-next",
      back: "onboarding-back",
      submit: "onboarding-submit",
    },
  },
  billing: {
    kindBusiness: "billing-kind-business",
    kindIndividual: "billing-kind-individual",
    ico: "billing-ico",
    billingName: "billing-name",
    addressStreet: "billing-address-street",
    addressCity: "billing-address-city",
    addressZip: "billing-address-zip",
    submit: "billing-submit",
  },
} as const;
